# Use official Python slim image
FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Copy requirements and install dependencies
COPY requirements.streamlit.txt .
RUN pip install --no-cache-dir -r requirements.streamlit.txt

# Copy app and model
COPY streamlit_app.py .

# Expose FastAPI port
EXPOSE 8501

# Command to run FastAPI with uvicorn
CMD ["streamlit", "run", "streamlit_app.py", "--server.address", "0.0.0.0", "--server.port", "8501"]